-- Bookify AI Supabase schema
-- Run this in Supabase SQL Editor after creating a Supabase project.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  email text not null unique,
  phone text,
  account_type text check (account_type in ('Customer', 'Business')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  owner_user_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,
  display_tag text not null unique,
  category text not null,
  subcategory text,
  custom_category text,
  location text not null,
  phone text not null,
  description text not null,
  price_per_hour numeric,
  currency_code text not null default 'INR',
  currency_symbol text not null default '₹',
  min_booking_hours integer not null default 1,
  max_booking_hours integer,
  buffer_time_between_slots integer not null default 0,
  image_url text,
  profile_image text,
  gallery_images text[] not null default '{}',
  opening_time text not null,
  closing_time text not null,
  closed_days text[] not null default '{}',
  is_booking_active boolean not null default true,
  is_active boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  customer_user_id uuid not null references public.profiles(id) on delete cascade,
  slot_date date not null,
  start_time text not null,
  end_time text not null,
  duration_hours integer not null,
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  status text not null default 'confirmed' check (status in ('confirmed', 'cancelled', 'completed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.slots (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  slot_date date not null,
  start_time text not null,
  end_time text not null,
  status text not null default 'available' check (status in ('available', 'booked', 'blocked')),
  block_reason text,
  booking_id bigint references public.bookings(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_slot unique (business_id, slot_date, start_time, end_time)
);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  business_id bigint not null references public.businesses(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  booking_id bigint references public.bookings(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  review_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  business_id bigint not null references public.businesses(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint uq_favorite unique (user_id, business_id)
);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_user_id uuid not null references public.profiles(id) on delete cascade,
  business_id bigint references public.businesses(id) on delete cascade,
  type text not null,
  title text not null,
  message text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists touch_profiles on public.profiles;
create trigger touch_profiles before update on public.profiles for each row execute function public.touch_updated_at();

drop trigger if exists touch_businesses on public.businesses;
create trigger touch_businesses before update on public.businesses for each row execute function public.touch_updated_at();

drop trigger if exists touch_slots on public.slots;
create trigger touch_slots before update on public.slots for each row execute function public.touch_updated_at();

drop trigger if exists touch_bookings on public.bookings;
create trigger touch_bookings before update on public.bookings for each row execute function public.touch_updated_at();

drop trigger if exists touch_reviews on public.reviews;
create trigger touch_reviews before update on public.reviews for each row execute function public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.businesses enable row level security;
alter table public.slots enable row level security;
alter table public.bookings enable row level security;
alter table public.reviews enable row level security;
alter table public.favorites enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles can read own profile" on public.profiles;
create policy "profiles can read own profile" on public.profiles for select using (auth.uid() = id);

drop policy if exists "profiles can create own profile" on public.profiles;
create policy "profiles can create own profile" on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "profiles can update own profile" on public.profiles;
create policy "profiles can update own profile" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "active businesses are public" on public.businesses;
create policy "active businesses are public" on public.businesses for select using (is_active = true);

drop policy if exists "business owners can manage businesses" on public.businesses;
create policy "business owners can manage businesses" on public.businesses for all using (auth.uid() = owner_user_id) with check (auth.uid() = owner_user_id);

drop policy if exists "visible slots can be read" on public.slots;
create policy "visible slots can be read" on public.slots for select using (
  status = 'available'
  or exists (select 1 from public.businesses b where b.id = slots.business_id and b.owner_user_id = auth.uid())
);

drop policy if exists "business owners can manage slots" on public.slots;
create policy "business owners can manage slots" on public.slots for all using (
  exists (select 1 from public.businesses b where b.id = slots.business_id and b.owner_user_id = auth.uid())
) with check (
  exists (select 1 from public.businesses b where b.id = slots.business_id and b.owner_user_id = auth.uid())
);

drop policy if exists "customers and owners can read bookings" on public.bookings;
create policy "customers and owners can read bookings" on public.bookings for select using (
  customer_user_id = auth.uid()
  or exists (select 1 from public.businesses b where b.id = bookings.business_id and b.owner_user_id = auth.uid())
);

drop policy if exists "customers can create own bookings" on public.bookings;
create policy "customers can create own bookings" on public.bookings for insert with check (customer_user_id = auth.uid());

drop policy if exists "customers and owners can update bookings" on public.bookings;
create policy "customers and owners can update bookings" on public.bookings for update using (
  customer_user_id = auth.uid()
  or exists (select 1 from public.businesses b where b.id = bookings.business_id and b.owner_user_id = auth.uid())
);

drop policy if exists "reviews are public" on public.reviews;
create policy "reviews are public" on public.reviews for select using (true);

drop policy if exists "customers create own reviews" on public.reviews;
create policy "customers create own reviews" on public.reviews for insert with check (user_id = auth.uid());

drop policy if exists "customers read own favorites" on public.favorites;
create policy "customers read own favorites" on public.favorites for select using (user_id = auth.uid());

drop policy if exists "customers manage own favorites" on public.favorites;
create policy "customers manage own favorites" on public.favorites for all using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "users read own notifications" on public.notifications;
create policy "users read own notifications" on public.notifications for select using (recipient_user_id = auth.uid());

drop policy if exists "users update own notifications" on public.notifications;
create policy "users update own notifications" on public.notifications for update using (recipient_user_id = auth.uid());
